resolver: lts-13.10

packages:
- argo
- cryptol-remote-api

extra-deps:
- deps/cryptol
- GraphSCC-1.0.4
- base-compat-0.9.3
- monadLib-3.9
- network-2.8.0.0
- panic-0.4.0.1
- simple-smt-0.9.3
- sbv-8.0
