resolver: lts-13.10

packages:
- argo
- cryptol-remote-api

extra-deps:
- deps/cryptol
- GraphSCC-1.0.4
- base-compat-0.10.5
- monadLib-3.9
- network-2.8.0.0
- panic-0.4.0.1
- simple-smt-0.9.4
- sbv-8.0

# stack's metadata gets out of date
# allow-newer: true
