name: argo

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.6.5", "8.8.4", "8.10.2"]
        package:
          - argo
          - python
          - file-echo-api
          - tasty-script-exitcode
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} - GHC v${{ matrix.ghc }} - ubuntu-latest
    steps:
      - uses: actions/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - uses: actions/cache@v2
        name: Cache cabal store
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ matrix.package }}-${{ matrix.ghc }}-${{ hashFiles('**/cabal.GHC-*') }}-${{ github.sha }}
          restore-keys: |
            cabal-${{ matrix.package }}-${{ matrix.ghc }}-${{ hashFiles('**/cabal.GHC-*') }}
      - name: Configure
        run: |
          cabal v2-update
          cabal v2-configure -j2 --minimize-conflict-set --enable-tests
      - name: Build
        run: cabal v2-build ${{ matrix.package }}
      - name: Tests
        working-directory: ${{ matrix.package }}
        run: cabal v2-test
